# Generated by Django 4.2.5 on 2023-11-21 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DevotionMonthDay",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("date_deleted", models.DateTimeField(blank=True, null=True)),
                ("month", models.TextField()),
                ("day", models.TextField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "-updated"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DevotionBibleReading",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("date_deleted", models.DateTimeField(blank=True, null=True)),
                (
                    "bible_reading_arrangement",
                    models.TextField(verbose_name="Bible Reading Arrangement"),
                ),
                (
                    "bible_reading_number",
                    models.TextField(blank=True, verbose_name="Bible Reading Number"),
                ),
                ("bible_reading", models.TextField(verbose_name="Bible Reading")),
                ("chapter", models.TextField(verbose_name="chapter")),
                ("from_verse", models.TextField(blank=True, verbose_name="From Verse")),
                ("to_verse", models.TextField(blank=True, verbose_name="To Verse")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "devotion_month_day_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devotion_month_day_id",
                        to="devotion.devotionmonthday",
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "-updated"],
                "abstract": False,
            },
        ),
    ]
