# Generated by Django 4.2.5 on 2023-11-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devotion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devotionbiblereading",
            name="bible_reading_arrangement",
            field=models.PositiveIntegerField(verbose_name="Bible Reading Arrangement"),
        ),
    ]
