# Generated by Django 4.2.5 on 2023-11-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devotion", "0002_alter_devotionbiblereading_bible_reading_arrangement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="devotionbiblereading",
            options={},
        ),
        migrations.AlterField(
            model_name="devotionbiblereading",
            name="bible_reading_arrangement",
            field=models.PositiveIntegerField(
                error_messages={
                    "unique_together": "This combination of devotion month day and Bible Reading Arrangement already exists."
                },
                verbose_name="Bible Reading Arrangement",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="devotionbiblereading",
            unique_together={("devotion_month_day_id", "bible_reading_arrangement")},
        ),
    ]
